# Generated by Django 3.2.5 on 2021-07-19 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorProfile',
            fields=[
                ('image', models.ImageField(blank=True, upload_to='profile/%Y/%m/%d', verbose_name='image')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('is_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
            ],
        ),
    ]
