# Generated by Django 3.2.5 on 2021-07-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile', verbose_name='image'),
        ),
    ]
