# Generated by Django 3.2.5 on 2021-07-26 09:51

import beer_collector.collector_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector_profile', '0002_alter_collectorprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to=beer_collector.collector_profile.models.image_upload_location, verbose_name='image'),
        ),
    ]
