# Generated by Django 3.2.5 on 2021-08-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='pub website'),
        ),
    ]
