# Generated by Django 3.2.5 on 2021-08-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pubs', verbose_name='pub image'),
        ),
    ]
